services:
  web:
    build: .
    ports:
      - "8088:80"
    volumes:
      - ./autoparts:/srv/http
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf:ro

  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: Clients_db
    volumes:
      - db_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    ports:
      - "3306:3306"

volumes:
  db_data: